MAGIC_REQUIRE_VARS := HYPERTABLE_HOME

MAGIC_FLAGS_CPPFLAGS := -I$(HYPERTABLE_HOME)/include
vpath %.a $(HYPERTABLE_HOME)/lib
vpath %.so $(HYPERTABLE_HOME)/lib

MAGIC_MODULE_DEPS := kdi
MAGIC_EXTERNAL_DEPS := Hypertable
MAGIC_LINK_TYPE := shared
include magic.mk
